// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "app/model"
)

// RepositoryAuth is an autogenerated mock type for the RepositoryAuth type
type RepositoryAuth struct {
	mock.Mock
}

// CountRecentFailedLoginAttempts provides a mock function with given fields: ctx, userID, sinceMinutes
func (_m *RepositoryAuth) CountRecentFailedLoginAttempts(ctx context.Context, userID int, sinceMinutes int) (int64, error) {
	ret := _m.Called(ctx, userID, sinceMinutes)

	if len(ret) == 0 {
		panic("no return value specified for CountRecentFailedLoginAttempts")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (int64, error)); ok {
		return rf(ctx, userID, sinceMinutes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) int64); ok {
		r0 = rf(ctx, userID, sinceMinutes)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, sinceMinutes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLoginAttempt provides a mock function with given fields: ctx, attempt
func (_m *RepositoryAuth) CreateLoginAttempt(ctx context.Context, attempt model.LoginAttempt) (model.LoginAttempt, error) {
	ret := _m.Called(ctx, attempt)

	if len(ret) == 0 {
		panic("no return value specified for CreateLoginAttempt")
	}

	var r0 model.LoginAttempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LoginAttempt) (model.LoginAttempt, error)); ok {
		return rf(ctx, attempt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.LoginAttempt) model.LoginAttempt); ok {
		r0 = rf(ctx, attempt)
	} else {
		r0 = ret.Get(0).(model.LoginAttempt)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.LoginAttempt) error); ok {
		r1 = rf(ctx, attempt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePasswordReset provides a mock function with given fields: ctx, reset
func (_m *RepositoryAuth) CreatePasswordReset(ctx context.Context, reset model.PasswordReset) (model.PasswordReset, error) {
	ret := _m.Called(ctx, reset)

	if len(ret) == 0 {
		panic("no return value specified for CreatePasswordReset")
	}

	var r0 model.PasswordReset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PasswordReset) (model.PasswordReset, error)); ok {
		return rf(ctx, reset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PasswordReset) model.PasswordReset); ok {
		r0 = rf(ctx, reset)
	} else {
		r0 = ret.Get(0).(model.PasswordReset)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PasswordReset) error); ok {
		r1 = rf(ctx, reset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSecurityEvent provides a mock function with given fields: ctx, event
func (_m *RepositoryAuth) CreateSecurityEvent(ctx context.Context, event model.SecurityEvent) (model.SecurityEvent, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecurityEvent")
	}

	var r0 model.SecurityEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SecurityEvent) (model.SecurityEvent, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.SecurityEvent) model.SecurityEvent); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(model.SecurityEvent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.SecurityEvent) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSession provides a mock function with given fields: ctx, session
func (_m *RepositoryAuth) CreateSession(ctx context.Context, session model.AuthSession) (model.AuthSession, error) {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 model.AuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AuthSession) (model.AuthSession, error)); ok {
		return rf(ctx, session)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AuthSession) model.AuthSession); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Get(0).(model.AuthSession)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AuthSession) error); ok {
		r1 = rf(ctx, session)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetailEmailVerification provides a mock function with given fields: ctx, tokenHash
func (_m *RepositoryAuth) DetailEmailVerification(ctx context.Context, tokenHash string) (model.EmailVerification, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DetailEmailVerification")
	}

	var r0 model.EmailVerification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.EmailVerification, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.EmailVerification); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(model.EmailVerification)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetailPasswordReset provides a mock function with given fields: ctx, tokenHash
func (_m *RepositoryAuth) DetailPasswordReset(ctx context.Context, tokenHash string) (model.PasswordReset, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DetailPasswordReset")
	}

	var r0 model.PasswordReset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PasswordReset, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PasswordReset); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(model.PasswordReset)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetailSessionByID provides a mock function with given fields: ctx, sessionID, userID
func (_m *RepositoryAuth) DetailSessionByID(ctx context.Context, sessionID string, userID int) (model.AuthSession, error) {
	ret := _m.Called(ctx, sessionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DetailSessionByID")
	}

	var r0 model.AuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (model.AuthSession, error)); ok {
		return rf(ctx, sessionID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) model.AuthSession); ok {
		r0 = rf(ctx, sessionID, userID)
	} else {
		r0 = ret.Get(0).(model.AuthSession)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, sessionID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetailSessionByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *RepositoryAuth) DetailSessionByTokenHash(ctx context.Context, tokenHash string) (model.AuthSession, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DetailSessionByTokenHash")
	}

	var r0 model.AuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.AuthSession, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.AuthSession); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(model.AuthSession)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSessions provides a mock function with given fields: ctx, userID
func (_m *RepositoryAuth) ListSessions(ctx context.Context, userID int) ([]model.AuthSession, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []model.AuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.AuthSession, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.AuthSession); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AuthSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkEmailVerificationUsed provides a mock function with given fields: ctx, verificationID
func (_m *RepositoryAuth) MarkEmailVerificationUsed(ctx context.Context, verificationID int) error {
	ret := _m.Called(ctx, verificationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailVerificationUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, verificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkPasswordResetUsed provides a mock function with given fields: ctx, resetID
func (_m *RepositoryAuth) MarkPasswordResetUsed(ctx context.Context, resetID int) error {
	ret := _m.Called(ctx, resetID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPasswordResetUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, resetID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeAllSessionsByUserID provides a mock function with given fields: ctx, userID
func (_m *RepositoryAuth) RevokeAllSessionsByUserID(ctx context.Context, userID int) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllSessionsByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeSessionByID provides a mock function with given fields: ctx, sessionID, userID
func (_m *RepositoryAuth) RevokeSessionByID(ctx context.Context, sessionID string, userID int) error {
	ret := _m.Called(ctx, sessionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSessionByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, sessionID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeSessionByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *RepositoryAuth) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSessionByTokenHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RotateSession provides a mock function with given fields: ctx, oldSessionID, session
func (_m *RepositoryAuth) RotateSession(ctx context.Context, oldSessionID int, session model.AuthSession) (model.AuthSession, error) {
	ret := _m.Called(ctx, oldSessionID, session)

	if len(ret) == 0 {
		panic("no return value specified for RotateSession")
	}

	var r0 model.AuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, model.AuthSession) (model.AuthSession, error)); ok {
		return rf(ctx, oldSessionID, session)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, model.AuthSession) model.AuthSession); ok {
		r0 = rf(ctx, oldSessionID, session)
	} else {
		r0 = ret.Get(0).(model.AuthSession)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, model.AuthSession) error); ok {
		r1 = rf(ctx, oldSessionID, session)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertEmailVerification provides a mock function with given fields: ctx, verification
func (_m *RepositoryAuth) UpsertEmailVerification(ctx context.Context, verification model.EmailVerification) (model.EmailVerification, error) {
	ret := _m.Called(ctx, verification)

	if len(ret) == 0 {
		panic("no return value specified for UpsertEmailVerification")
	}

	var r0 model.EmailVerification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.EmailVerification) (model.EmailVerification, error)); ok {
		return rf(ctx, verification)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.EmailVerification) model.EmailVerification); ok {
		r0 = rf(ctx, verification)
	} else {
		r0 = ret.Get(0).(model.EmailVerification)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.EmailVerification) error); ok {
		r1 = rf(ctx, verification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepositoryAuth creates a new instance of RepositoryAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryAuth {
	mock := &RepositoryAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
