// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "app/model"
)

// RepositoryOrganization is an autogenerated mock type for the RepositoryOrganization type
type RepositoryOrganization struct {
	mock.Mock
}

// CreateOrganization provides a mock function with given fields: ctx, organization
func (_m *RepositoryOrganization) CreateOrganization(ctx context.Context, organization model.Organization) (model.Organization, error) {
	ret := _m.Called(ctx, organization)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 model.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Organization) (model.Organization, error)); ok {
		return rf(ctx, organization)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Organization) model.Organization); ok {
		r0 = rf(ctx, organization)
	} else {
		r0 = ret.Get(0).(model.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Organization) error); ok {
		r1 = rf(ctx, organization)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepositoryOrganization creates a new instance of RepositoryOrganization. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryOrganization(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryOrganization {
	mock := &RepositoryOrganization{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
