// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	authv1 "app/gen/auth/v1"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ServiceAuth is an autogenerated mock type for the ServiceAuth type
type ServiceAuth struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) ChangePassword(ctx context.Context, req *authv1.ChangePasswordRequest) (*authv1.AuthStatusResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 *authv1.AuthStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ChangePasswordRequest) (*authv1.AuthStatusResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ChangePasswordRequest) *authv1.AuthStatusResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.AuthStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.ChangePasswordRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ForgotPassword provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) ForgotPassword(ctx context.Context, req *authv1.ForgotPasswordRequest) (*authv1.ForgotPasswordResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 *authv1.ForgotPasswordResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ForgotPasswordRequest) (*authv1.ForgotPasswordResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ForgotPasswordRequest) *authv1.ForgotPasswordResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.ForgotPasswordResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.ForgotPasswordRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSessions provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) ListSessions(ctx context.Context, req *authv1.ListSessionsRequest) (*authv1.ListSessionsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 *authv1.ListSessionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ListSessionsRequest) (*authv1.ListSessionsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ListSessionsRequest) *authv1.ListSessionsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.ListSessionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.ListSessionsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) Login(ctx context.Context, req *authv1.LoginRequest) (*authv1.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *authv1.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LoginRequest) (*authv1.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LoginRequest) *authv1.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) Logout(ctx context.Context, req *authv1.LogoutRequest) (*authv1.AuthStatusResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 *authv1.AuthStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LogoutRequest) (*authv1.AuthStatusResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LogoutRequest) *authv1.AuthStatusResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.AuthStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.LogoutRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogoutAll provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) LogoutAll(ctx context.Context, req *authv1.LogoutAllRequest) (*authv1.AuthStatusResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 *authv1.AuthStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LogoutAllRequest) (*authv1.AuthStatusResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.LogoutAllRequest) *authv1.AuthStatusResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.AuthStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.LogoutAllRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) RefreshToken(ctx context.Context, req *authv1.RefreshTokenRequest) (*authv1.RefreshTokenResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *authv1.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RefreshTokenRequest) (*authv1.RefreshTokenResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RefreshTokenRequest) *authv1.RefreshTokenResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.RefreshTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.RefreshTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) Register(ctx context.Context, req *authv1.RegisterRequest) (*authv1.RegisterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *authv1.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RegisterRequest) (*authv1.RegisterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RegisterRequest) *authv1.RegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResendEmailVerification provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) ResendEmailVerification(ctx context.Context, req *authv1.ResendEmailVerificationRequest) (*authv1.AuthStatusResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResendEmailVerification")
	}

	var r0 *authv1.AuthStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ResendEmailVerificationRequest) (*authv1.AuthStatusResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ResendEmailVerificationRequest) *authv1.AuthStatusResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.AuthStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.ResendEmailVerificationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPassword provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) ResetPassword(ctx context.Context, req *authv1.ResetPasswordRequest) (*authv1.AuthStatusResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 *authv1.AuthStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ResetPasswordRequest) (*authv1.AuthStatusResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.ResetPasswordRequest) *authv1.AuthStatusResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.AuthStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.ResetPasswordRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeSession provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) RevokeSession(ctx context.Context, req *authv1.RevokeSessionRequest) (*authv1.AuthStatusResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 *authv1.AuthStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RevokeSessionRequest) (*authv1.AuthStatusResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.RevokeSessionRequest) *authv1.AuthStatusResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.AuthStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.RevokeSessionRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyEmail provides a mock function with given fields: ctx, req
func (_m *ServiceAuth) VerifyEmail(ctx context.Context, req *authv1.VerifyEmailRequest) (*authv1.AuthStatusResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 *authv1.AuthStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.VerifyEmailRequest) (*authv1.AuthStatusResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *authv1.VerifyEmailRequest) *authv1.AuthStatusResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.AuthStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *authv1.VerifyEmailRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceAuth creates a new instance of ServiceAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceAuth {
	mock := &ServiceAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
